### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tag'

### ISSUE THREAD

**Issue by 0x10** [0x10/obmenu2#10]
Reproduction scenario:
Open a XML
select an entry which is of type execute
open another xml
watch log output

**Comment by 0x10** [comment]
Traceback (most recent call last):
  File "./obmenu2", line 1178, in on_label_changed
    widget.get_text())
  File "./obmenu2", line 372, in set_label
    self.set_label(self.get_parent(item), label)
  File "./obmenu2", line 366, in set_label
    if self.strip_ns(item.tag) == "item":
AttributeError: 'NoneType' object has no attribute 'tag'
